### ISSUE TITLE
Server Crashes On Startup (while registering commands)

### ISSUE THREAD

**Issue by Charmanth** [FTBTeam/FTB-Essentials#1]
There's no crash report to pastebin.  The mods all work together client-side, but on a server ftb-essentials crashes the server while registering commands (if the console is anything to go by).  Error I get is:  [Server] main/ERROR [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: java.lang.NoSuchMethodError: net.minecraft.stats.IStatFormatter.format(I)Ljava/lang/String;

After that are lines involving registering commands from ftb essentials and other mods.  

Edit: Mod version 1603.1.0.4

**Comment by CapitanCJ** [comment]
I am having this issue as well

**Comment by shenniko** [comment]
Can confirm i have this issue also:

https://pastebin.com/YRXVfcPc

Removing this mod and the everything loads fine

Minecraft Version: 1.16.3
Forge Version: 34.1.16
Mod Version: ftbessentials-1603.1.0.4.jar

**Comment by zoyer2** [comment]
same here
[latest.log](https://github.com/FTBTeam/FTB-Essentials/files/5360342/latest.log)
[debug.log](https://github.com/FTBTeam/FTB-Essentials/files/5360345/debug.log)

**Comment by Ocraftyone** [comment]
i know that this would happen on 1.12.2. when you didn't have the ftb library mod installed as well
