### ISSUE TITLE
fly for no-ops

### ISSUE THREAD

**Issue by UnFOURJhinate** [FTBTeam/FTB-Essentials#11]
So i tried giving non ops the ability to fly but it doesn´t seem to work :( Any suggestions? thanks

**Comment by MaxNeedsSnacks** [comment]
You can use FTB Ranks to configure specific ranks that have the ability to fly, for more info, see the (WIP) FTB Ranks Wiki:

https://help.ftb.team/help/en-gb/6-ftb-ranks

(in this case, you would want to restrict `command.fly` to certain ranks
)
