### ISSUE TITLE
issue using /sethome

### ISSUE THREAD

**Issue by tekman123** [FTBTeam/FTB-Essentials#14]
using FTB Essentials 1604.1.0.13 I can use /sethome [home name here] but even after fresh world and config generation it says too many homes. I checked the list of homes and none are listed for myself or the other player on my server and yet neither of us can use /sethome

**Comment by MaxNeedsSnacks** [comment]
Is this still an issue in more recent versions? Something might be wrong with either your config or your ranks setup
