### ISSUE TITLE
No config files

### ISSUE THREAD

**Issue by Nagispace** [FTBTeam/FTB-Essentials#2]
I'm unable to find the config file in the "config" folder.

**Comment by Crystallyne** [comment]
I am having this issue as well. Specifically I want to change the limit of how many homes a player can have for the /home command. There is no config file in the config folder, nor are there any associated files in the local folder.

**Comment by Nagispace** [comment]
> I am having this issue as well. Specifically I want to change the limit of how many homes a player can have for the /home command. There is no config file in the config folder, nor are there any associated files in the local folder.

I just found the solution today.
The config files are located in the world save folder.
You should be able to find them easily in there.
