### ISSUE TITLE
Not available on the server

### ISSUE THREAD

**Issue by JVhuaA** [FTBTeam/FTB-Essentials#29]
None but the administrator has permission to use the command.
The configuration file is not restricted to players at all after reading it, but it is not available in the game at all.
Please tell me if there is another setting.
Regarding plugins, there is only one store plugin in the server.
I hope to get your help.Thank you.

**Comment by JVhuaA** [comment]
The configuration file is all true, should it be changed to false？

**Comment by MaxNeedsSnacks** [comment]
If you're using a custom server or server mod framework, like Mohist or Sponge, we unfortunately can't guarantee that any of our mods will work, as they rely on the permissions system provided by FTB Ranks / Forge itself
