### ISSUE TITLE
Unable to Configure /home Permissions

### ISSUE THREAD

**Issue by Crystallyne** [FTBTeam/FTB-Essentials#3]
I cannot find a config file or any other file to edit to change the number of homes a user can have for the /home command. There is absolutely no files associated with this mod either in the config folder, or in the local folder. I am playing in single player mode on a custom mod pack of my own making. I even added the FTB Ranks mod hoping it would allow me to edit how many /home locations I can have.

Someone else posted an issue that they couldn't find any config file for this mod, and then later said they found it in the World Save folder. I think I found the file they're talking about, but I don't see anything there to allow me to change the number of homes I can have. Even if that did work, it would only affect that one save.

Can anyone help me figure this out, please?

**Comment by Crystallyne** [comment]
I did eventually figure out how to change this per save file, but it would still be nice to have a config file that affects ALL save files, instead of having to do it for each one.

For anyone who may find this, wondering where to find the option: Open the folder where your game is and go to saves > "World Name" (the name of your save) > serverconfig > ftbessentials-server.toml. Look for "maxHomes" and change it from 1 to however many homes you want. (It's the 6th line down, in my file.)

**Comment by MacChuck** [comment]
Is this a 1.16 change? Seems like there's a ton of stuff stored in the world folder now.

**Comment by Linguardium** [comment]
there is a defaultconfigs folder you can create in the instance/profile (next to configs and mods) where you can put the default serverconfig files

**Comment by GraNychtiNe** [comment]
after modifying the ftbessentials-server.toml file in the defaultconfig folder, in the server the configuration is not taken into account. What to do ?

**Comment by Linguardium** [comment]
the defaultconfig is only used when first creating the server. once the world is generated you must edit the config in the world folder/serverconfigs/
