### ISSUE TITLE
Cooldowns expire on server restart

### ISSUE THREAD

**Issue by DeathOfTime** [FTBTeam/FTB-Essentials#5]
ATM6 1.3.3 test version
FTB essentials 1603.1.0.11

When the server is restarted the cooldowns are all reset.

To reproduce:
set cooldowns to max in config file. this step isn't needed on the ATM6 packs as it is already that way
use /spawn
immediately use spawn again and note the real world cooldown time
immediately restart server
use /spawn
note that it works even though it should still have six days and 23 hours before it should

Expected behavior:
cooldowns to take the full time they are set to

duplicating this here. i hope you don't mind
https://github.com/AllTheMods/ATM-6/issues/513

**Comment by MaxNeedsSnacks** [comment]
We probably won't be fixing this as there is in my opinion very little use for a scenario where a cooldown is larger than the average server restart period (which is usually ~6-12 hours), or at least not enough use to justify saving every player's teleport cooldowns to disk
