### ISSUE TITLE
Issue with doing /setworldspawn and /spawn

### ISSUE THREAD

**Issue by ModernGamingWorld** [FTBTeam/FTB-Essentials#6]
Whenever I use /setworldspawn any players joining the server for the first time, doe not end up at where I ran the command and when they do /spawn that they end up on top of spawn and not where /setworldspawn was set at

**Comment by ajlittle** [comment]
Some further information, even with /gamerule spawnRadius 0 it still happens.

**Comment by storiofmylife** [comment]
I also have this issue. Spawn is on the bottom floor of the building with 0 radius and it still spawns people on the roof of the building when they use /spawn.

**Comment by mrdeadlocked** [comment]
same issue
