### ISSUE TITLE
Listhomes and listWarps

### ISSUE THREAD

**Issue by Mini-kun** [FTBTeam/FTB-Essentials#8]
Hello FTB

my bug/error is not even reply in the console with anything and it just don't send any output out after a update from a older version to the newse version i update the mod 2 day ago and it just stop working 

versions:
Forge 34.0.14
Minecraft 1.16.5
Essentials: 1604.1.0.13
Ranks 1604.1.1.10
Teams: 1604.1.0.15
Chunks: 1604.2.2.62
Library 1605.2.1.37-Forge

**Comment by MaxNeedsSnacks** [comment]
This shouldn't be an issue in newer versions, hopefully
